export const ValueConstants = {
  DEFAULT_QUALITY: 85,
  QUALITY_MAX_VALUE: 100,
  QUALITY_MIN_VALUE: 1,
  OPTIONS_MAX_LENGTH: 5,
  OPTIONS_MIN_LENGTH: 1,
  HEIGHT_MIN_VALUE: 1,
  WIDTH_MIN_VALUE: 1,
};
