export const ValueConstants = Object.freeze({
  DEFAULT_QUALITY: 85,
  QUALITY_MAX_VALUE: 100,
  QUALITY_MIN_VALUE: 1,
  OPTIONS_MAX_LENGTH: 5,
  OPTIONS_MIN_LENGTH: 1,
  HEIGHT_MIN_VALUE: 1,
  WIDTH_MIN_VALUE: 1,
  CONTENT_LENGTH_SIZE: 1 * 1024 * 1024,
});
